akka.http.parsing.cookie-parsing-mode = raw
akka.http.server.request-timeout = 60s

lego-taxonomy.web {
  route-request = 30s
  data-ask = 10s
  process-ask = 20s
  image-wait = 10s
  image-retry-after = 2s
  image-negative-ttl = 24h
}
